import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Trending from "../components/Trending";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section></section>
        <section>
          <div className={styles.inputWrapper}>
            <div className={styles.iconWrapper}>
              <Image
                src={
                  "https://cdn.icon-icons.com/icons2/2551/PNG/512/search_icon_152764.png"
                }
                layout="fill"
              />
            </div>
            <input type="text" placeholder='Try "Primates NFT"' />
          </div>
          {/* LINKS------------- */}
          <nav className={styles.navLinks}>
            <a href={`#`} className={styles.active}>
              Explore
            </a>
            <a href={`#`}>Stats</a>
            <a href={`#`}>Resources</a>
            <a href={`#`}>Collections</a>
            <a href={`#`}>Create</a>
          </nav>
          {/* CARD--------------- */}
          <div className={styles.card}>
            <div className={styles.left}>
              <h1>Discover the biggest NFT Marketplace.</h1>
              <button>Discover now</button>
            </div>
            <div className={styles.middle}></div>
            <div className={styles.right}>
              <Image src={"/ethGolden.png"} layout="fill" />
            </div>
          </div>
          {/* TRENDING------------- */}

          <Trending />
        </section>
        <section></section>
      </main>
    </div>
  );
}
